In [1]:
import pickle

with open('model_dict.p', 'rb') as handle:
    result = pickle.load(handle)

/Users/allard/anaconda3/envs/dev/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.21.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/allard/anaconda3/envs/dev/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
/Users/allard/anaconda3/envs/dev/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.21.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


<class 'dict'>


In [64]:
for k, v in result.items():
    print(k)

Compile After Delivery
Virtualization/Sandbox Evasion
Resource Hijacking
Stored Data Manipulation
Inhibit System Recovery
Service Stop
Disk Content Wipe
Disk Structure Wipe
Data Encrypted for Impact
Data Destruction
Group Policy Modification
Domain Generation Algorithms
Domain Trust Discovery
Execution Guardrails
File Permissions Modification
Compiled HTML File
Template Injection
XSL Script Processing
Browser Bookmark Discovery
Data from Information Repositories
Exploit Public-Facing Application
Exploitation of Remote Services
Spearphishing via Service
Trusted Relationship
CMSTP
DCShadow
Drive-by Compromise
Signed Binary Proxy Execution
Spearphishing Attachment
Supply Chain Compromise
User Execution
Control Panel Items
BITS Jobs
Credentials in Registry
Spearphishing Link
Sudo Caching
Exploitation for Client Execution
Kerberoasting
Password Policy Discovery
Port Knocking
Remote Access Tools
Domain Fronting
Dynamic Data Exchange
Forced Authentication
Multi-hop Proxy
Distributed Component

In [10]:
len(result.items())   # 201 should be the number of attack techniques with models built

201

In [73]:
for k, v in result.items():
    print(type(v[0]))
    print(type(v[1]))
    break

<class 'sklearn.feature_extraction.text.CountVectorizer'>
<class 'sklearn.linear_model._logistic.LogisticRegression'>


In [12]:
model = result['Commonly Used Port']

## Dealing with Preprocessing

In [19]:
print(model[0])
type(model[0])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=2000, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


sklearn.feature_extraction.text.CountVectorizer

In [116]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = model[0]
X = vectorizer.fit_transform(corpus)

In [117]:
print(vectorizer.get_feature_names())
print(X.toarray())

['and this', 'document is', 'first document', 'is the', 'is this', 'second document', 'the first', 'the second', 'the third', 'third one', 'this document', 'this is', 'this the']
[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]


In [61]:
vectorizer2 = model[0]
vectorizer2.ngram_range = (2,2)
vectorizer2

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=2000, min_df=1,
                ngram_range=(2, 2), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [62]:
X2 = vectorizer2.fit_transform(corpus)
print(vectorizer2.get_feature_names())

['and this', 'document is', 'first document', 'is the', 'is this', 'second document', 'the first', 'the second', 'the third', 'third one', 'this document', 'this is', 'this the']


## Dealing with Model

In [83]:
print(model[1], '\n')
print(model[1].get_params(), '\n')
print(model[1].classes_)
type(model[1])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=2500,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False) 

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 2500, 'multi_class': 'warn', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False} 

[False  True]


sklearn.linear_model._logistic.LogisticRegression

### Predict on Dummy Data

In [44]:
import numpy as np
test = [[3,4]*1000]
tarr = np.array(test)
tarr.reshape(1, -1)

array([[3, 4, 3, ..., 4, 3, 4]])

In [45]:
tarr.shape

(1, 2000)

In [46]:
model[1].predict(tarr)

array([False])

### Predict on Sample Text

In [118]:
X.shape

(4, 13)

In [121]:
X.toarray()

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1]])

In [124]:
from keras.preprocessing.sequence import pad_sequences
X_pred = pad_sequences(X.toarray(), padding='post', maxlen=2000)
X_pred.shape

(4, 2000)

In [125]:
model[1].predict(X_pred)

array([False, False, False, False])

### Summarised Prediction Process

In [172]:
port_corpus = ['attempted to contact the C2 server over TCP using port 80.', 'uses port 443 for the control server communications.', 'uses port 443 for C2.', 'variants can use ports 443, 8443, and 8080 for communications.', 'has used ports 53, 80, 443, and 8080 for C2.', 'used SMB over ports 445 or 139 for C2. The group also established encrypted connections over port 443.', 'uses port 8000 and 443 for C2.', 'uses Port Numbers 443 and 80 for the C2 server.', 'uses port 80 for C2.', 'used TCP port 80 for C2.', 'uses 443 for C2 communications.', 'uses port 80 for C2.', 'uses Port Numbers 80, 8080, 8000, and 443 for communication to the C2 servers.', 'binds and listens on port 443.', 'uses port 443 for C2 communications.', 'uses port 443 for C2 communications.', 'uses port 443 for C2.', 'has used port 8080 for C2.', 'has tunneled RDP backdoors over port 443.', 'connects to external C2 infrastructure over port 443.', 'connects to external C2 infrastructure over port 443.', 'connects to external C2 infrastructure over the HTTP port.', 'has used port 80 for C2.', 'connects to external C2 infrastructure and opens a backdoor over port 443.', 'uses commonly used ports (like HTTPS/443) for command and control.', 'malware has communicated with C2 servers over port 6667 (for IRC) and port 8080.', 'A variant of  attempts communication to the C2 server over HTTP on port 443.', 'uses HTTP over port 443 for command and control.', 'Some  variants use ports 8080 and 8000 for C2.', 'uses a custom command and control protocol that communicates over commonly used ports. The C2 protocol is encapsulated in common application layer protocols.', 'communicates over common ports such as TCP 80, 443, and 25.', 'communicates with its C2 domain over ports 443 and 8443.', 'connects over 443 for C2.', 'communicates with its C2 server over port 443.', 'communicates over ports 80, 443, 53, and 8080 via raw sockets instead of the protocols usually associated with the ports.', 'uses a specific port of 443 and can also use ports 53 and 80 for C2. One  variant uses HTTP over port 443 to connect to its C2 server.', 'uses a custom command and control protocol that communicates over commonly used ports, and is frequently encapsulated by application layer protocols.', 'One  variant connected to its C2 server over port 8080.', 'operates over ports 21 and 20.', 'command and control occurs via HTTPS over port 443.', 'network traffic communicates over common ports like 80, 443, or 1433.', 'beacons to destination port 443.', 'uses ports 80, 443, and 8080 for C2.', 'has beaconed to its C2 over port 443.', 'is a RAT that communicates with HTTP.', 'communicates over port 80 for C2.', 'has used TCP port 8080 for C2.', 'uses HTTP TCP port 80 and HTTPS TCP port 443 for communications.', 'uses port 8080 for C2.', 'Some  malware uses a list of ordered port numbers to choose a port for C2 traffic, which includes commonly used ports such as 443, 53, 80, 25, and 8080.', 'C2 traffic for most  tools occurs over Port Numbers 53, 80, and 443.']
port_corpus

['attempted to contact the C2 server over TCP using port 80.',
 'uses port 443 for the control server communications.',
 'uses port 443 for C2.',
 'variants can use ports 443, 8443, and 8080 for communications.',
 'has used ports 53, 80, 443, and 8080 for C2.',
 'used SMB over ports 445 or 139 for C2. The group also established encrypted connections over port 443.',
 'uses port 8000 and 443 for C2.',
 'uses Port Numbers 443 and 80 for the C2 server.',
 'uses port 80 for C2.',
 'used TCP port 80 for C2.',
 'uses 443 for C2 communications.',
 'uses port 80 for C2.',
 'uses Port Numbers 80, 8080, 8000, and 443 for communication to the C2 servers.',
 'binds and listens on port 443.',
 'uses port 443 for C2 communications.',
 'uses port 443 for C2 communications.',
 'uses port 443 for C2.',
 'has used port 8080 for C2.',
 'has tunneled RDP backdoors over port 443.',
 'connects to external C2 infrastructure over port 443.',
 'connects to external C2 infrastructure over port 443.',
 'connects

In [129]:
len(port_corpus)

51

In [137]:
vect = model[0]
X1 = vect.fit_transform(port_corpus)
X1.toarray().shape

(51, 237)

In [209]:
X1.toarray()[43]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [208]:
X1.toarray()[42]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
from keras.preprocessing.sequence import pad_sequences
X1_pred = pad_sequences(X1.toarray(), padding='post', maxlen=2000)
X1_pred.shape

(51, 2000)

In [211]:
X1_pred[42].shape

(2000,)

In [213]:
X1_pred[42][:20]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
      dtype=int32)

In [214]:
predictions = model[1].predict(X1_pred)
predictions

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [142]:
probs = model[1].predict_proba(X1_pred)
probs

array([[0.96101292, 0.03898708],
       [0.99555442, 0.00444558],
       [0.99514826, 0.00485174],
       [0.99517025, 0.00482975],
       [0.99511116, 0.00488884],
       [0.99673549, 0.00326451],
       [0.99541592, 0.00458408],
       [0.99508661, 0.00491339],
       [0.99515075, 0.00484925],
       [0.9947261 , 0.0052739 ],
       [0.9948971 , 0.0051029 ],
       [0.99515075, 0.00484925],
       [0.99278744, 0.00721256],
       [0.99520416, 0.00479584],
       [0.99513909, 0.00486091],
       [0.99513909, 0.00486091],
       [0.99514826, 0.00485174],
       [0.99538941, 0.00461059],
       [0.99507756, 0.00492244],
       [0.96026348, 0.03973652],
       [0.96026348, 0.03973652],
       [0.95973276, 0.04026724],
       [0.99526616, 0.00473384],
       [0.94813659, 0.05186341],
       [0.99575476, 0.00424524],
       [0.99742518, 0.00257482],
       [0.99409958, 0.00590042],
       [0.99527576, 0.00472424],
       [0.99166936, 0.00833064],
       [0.99600397, 0.00399603],
       [0.

In [148]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/allard/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [174]:
for s in port_corpus:
    print(s)

attempted to contact the C2 server over TCP using port 80.
uses port 443 for the control server communications.
uses port 443 for C2.
variants can use ports 443, 8443, and 8080 for communications.
has used ports 53, 80, 443, and 8080 for C2.
used SMB over ports 445 or 139 for C2. The group also established encrypted connections over port 443.
uses port 8000 and 443 for C2.
uses Port Numbers 443 and 80 for the C2 server.
uses port 80 for C2.
used TCP port 80 for C2.
uses 443 for C2 communications.
uses port 80 for C2.
uses Port Numbers 80, 8080, 8000, and 443 for communication to the C2 servers.
binds and listens on port 443.
uses port 443 for C2 communications.
uses port 443 for C2 communications.
uses port 443 for C2.
has used port 8080 for C2.
has tunneled RDP backdoors over port 443.
connects to external C2 infrastructure over port 443.
connects to external C2 infrastructure over port 443.
connects to external C2 infrastructure over the HTTP port.
has used port 80 for C2.
connects t

In [197]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import RegexpTokenizer

sents_tokenized = []
for sentence in port_corpus:
    # * Remove stopwords
    sw = nltk.corpus.stopwords.words('english')
    regex_tokenizer = RegexpTokenizer('\w+')        # Regex to select all (and only) words from the sentence
    tokens = regex_tokenizer.tokenize(sentence)

    ns_words = []
    for word in tokens:
        if word.lower() not in sw:
            ns_words.append(word.lower())

    # * Stemming
    ps = PorterStemmer() 

    stemmed_sentence = ''
    for word in ns_words:
        stem_word = ps.stem(word)
        stem_word += ' '
        stemmed_sentence += stem_word
    print(stemmed_sentence)
    sent_tokenized = vect.fit_transform([stemmed_sentence])
    
    sent_pad = pad_sequences(sent_tokenized.toarray(), padding='post', maxlen=2000)
    print(sent_pad)
    sents_tokenized.append(sent_pad)

attempt contact c2 server tcp use port 80 
[[1 1 1 ... 0 0 0]]
use port 443 control server commun 
[[1 1 1 ... 0 0 0]]
use port 443 c2 
[[1 1 1 ... 0 0 0]]
variant use port 443 8443 8080 commun 
[[1 1 1 ... 0 0 0]]
use port 53 80 443 8080 c2 
[[1 1 1 ... 0 0 0]]
use smb port 445 139 c2 group also establish encrypt connect port 443 
[[1 1 1 ... 0 0 0]]
use port 8000 443 c2 
[[1 1 1 ... 0 0 0]]
use port number 443 80 c2 server 
[[1 1 1 ... 0 0 0]]
use port 80 c2 
[[1 1 1 ... 0 0 0]]
use tcp port 80 c2 
[[1 1 1 ... 0 0 0]]
use 443 c2 commun 
[[1 1 1 ... 0 0 0]]
use port 80 c2 
[[1 1 1 ... 0 0 0]]
use port number 80 8080 8000 443 commun c2 server 
[[1 1 1 ... 0 0 0]]
bind listen port 443 
[[1 1 1 ... 0 0 0]]
use port 443 c2 commun 
[[1 1 1 ... 0 0 0]]
use port 443 c2 commun 
[[1 1 1 ... 0 0 0]]
use port 443 c2 
[[1 1 1 ... 0 0 0]]
use port 8080 c2 
[[1 1 1 ... 0 0 0]]
tunnel rdp backdoor port 443 
[[1 1 1 ... 0 0 0]]
connect extern c2 infrastructur port 443 
[[1 1 1 ... 0 0 0]]
connect ext

In [199]:
for s in sents_tokenized:
    print(s.shape)
print(type(sents_tokenized))
len(sents_tokenized)

(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
(1, 2000)
<class 'list'>


51

In [200]:
PREDS = model[1].predict(sents_tokenized)
PREDS

ValueError: Found array with dim 3. Estimator expected <= 2.